[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["python311", "pip311"]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements-core.txt"
]

[start]
cmd = "python app.py"

